In [1]:
import numpy as np
import pandas as pd

##### 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

##### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [4]:
arr2 = np.arange(0,9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [5]:
arr3 = np.random.randint(1,100,20).reshape(5,4)
arr3

array([[53,  6, 91, 84],
       [97, 16,  5, 31],
       [97, 81, 81, 11],
       [16, 43, 13, 38],
       [ 7, 15, 69, 95]], dtype=int32)

In [6]:
arr3.shape

(5, 4)

In [7]:
arr3.size

20

##### 5. Create a 3x3 array of integers and access:

In [8]:
arr5 = np.random.randint(1,100,9).reshape(3,3)
arr5

array([[85, 22, 88],
       [38, 62, 74],
       [47, 20, 53]], dtype=int32)

###### a. The second element of the first row.

In [9]:
arr5[0,1]

np.int32(22)

###### b. The third column of the 2nd row.

In [10]:
arr5[1,2]

np.int32(74)

###### c. A subarray with the first two rows and last two columns.

In [11]:
arr5[0:2, 1:3]

array([[22, 88],
       [62, 74]], dtype=int32)

##### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [12]:
arr6 = np.arange(1,13)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
arr6 = arr6.reshape(3,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##### 7. Reshape a 3x3 matrix into a 1D array.

In [15]:
arr7 = np.random.randint(1,50,9).reshape(3,3)
arr7

array([[11, 39, 22],
       [26, 47,  3],
       [15, 42,  7]], dtype=int32)

In [16]:
arr7 = arr5.reshape(9)
arr7

array([85, 22, 88, 38, 62, 74, 47, 20, 53], dtype=int32)

##### 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [17]:
arr8 = np.random.randint(1,50,6).reshape(2,3)
arr8

array([[48,  4, 13],
       [13,  8, 40]], dtype=int32)

In [18]:
arr9 = np.random.randint(1,50,6).reshape(2,3)
arr9

array([[24,  4, 20],
       [37, 46, 24]], dtype=int32)

In [19]:
arr8 + arr9

array([[72,  8, 33],
       [50, 54, 64]], dtype=int32)

In [20]:
arr8 - arr9

array([[ 24,   0,  -7],
       [-24, -38,  16]], dtype=int32)

In [21]:
arr8 * arr9

array([[1152,   16,  260],
       [ 481,  368,  960]], dtype=int32)

In [22]:
arr8 / arr9

array([[2.        , 1.        , 0.65      ],
       [0.35135135, 0.17391304, 1.66666667]])

##### 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [23]:
arr10 = np.arange(1,100,12)
arr10

array([ 1, 13, 25, 37, 49, 61, 73, 85, 97])

In [24]:
arr10.sum()

np.int64(441)

In [25]:
arr10.mean()

np.float64(49.0)

In [26]:
arr10.std()

np.float64(30.983866769659336)

##### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [27]:
A = np.random.randint(1,50,4).reshape(2,2)
A

array([[43, 31],
       [ 4, 15]], dtype=int32)

In [28]:
B = np.random.randint(1,50,4).reshape(2,2)
B

array([[10, 28],
       [13, 43]], dtype=int32)

In [29]:
result = np.dot(A, B)
result

array([[ 833, 2537],
       [ 235,  757]], dtype=int32)

In [30]:
result1 = A @ B
result1

array([[ 833, 2537],
       [ 235,  757]], dtype=int32)

##### 11. Find the transpose of matrix A and matrix B.

In [31]:
A_transpose = A.T
B_transpose = B.T

In [32]:
A_transpose

array([[43,  4],
       [31, 15]], dtype=int32)

In [33]:
B_transpose

array([[10, 13],
       [28, 43]], dtype=int32)

##### 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [34]:
P = np.random.randint(1,100,9).reshape(3,3)
P

array([[81, 76, 99],
       [38, 56, 86],
       [ 4,  8,  6]], dtype=int32)

In [35]:
Q = np.random.randint(1,100,3)
Q

array([86, 47,  6], dtype=int32)

In [36]:
R = P + Q
R

array([[167, 123, 105],
       [124, 103,  92],
       [ 90,  55,  12]], dtype=int32)

In [37]:
# Broadcasting allows NumPy to perform operations on arrays of different shapes. Here, the 1D array is automatically expanded and treated as if it is repeated for each row of the 3×3 array. Then, element-wise addition is done.

##### 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [38]:
arr13 = np.random.randint(1,100,16).reshape(4,4)
arr13

array([[40, 93, 16,  4],
       [57, 43, 89, 98],
       [39, 57, 39, 91],
       [63, 35, 93, 53]], dtype=int32)

In [39]:
arr13.min()

np.int32(4)

In [40]:
arr13.max()

np.int32(98)

In [41]:
arr13.mean()

np.float64(56.875)

##### 14. Find the row-wise and column-wise sums.

In [42]:
arr14 = np.random.randint(1,50,16).reshape(4,4)
arr14

array([[48, 33, 37, 12],
       [35, 29, 14, 12],
       [ 6,  8, 45, 27],
       [18, 41, 20, 11]], dtype=int32)

In [43]:
row_sum = arr14.sum(axis=1)
row_sum

array([130,  90,  86,  90])

In [44]:
col_sum = arr14.sum(axis=0)
col_sum

array([107, 111, 116,  62])

##### 15. Generate an array of 10 random integers between 1 and 50.

In [45]:
arr12 = np.random.randint(1,50,10)
arr12

array([35, 40, 41,  6, 22,  1, 32, 17, 27, 28], dtype=int32)

##### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [46]:
arr13 = np.random.rand(25).reshape(5,5)
arr13

array([[3.38685714e-01, 6.87586484e-01, 7.00423028e-01, 1.05802541e-01,
        2.65687053e-01],
       [4.16182820e-01, 7.58407454e-01, 7.58749748e-01, 9.66229295e-01,
        2.09356329e-01],
       [3.53050274e-01, 9.13829107e-01, 3.55817369e-01, 4.78301591e-01,
        9.79528224e-01],
       [2.19687793e-01, 2.93823540e-01, 5.36702455e-05, 3.73178997e-03,
        4.76836718e-01],
       [4.93486458e-01, 8.36760293e-01, 1.53288612e-01, 4.13890312e-01,
        6.18050766e-01]])